[package]
name = "unfair_flips"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
csv = "1.4.0"
fastrand = "2.3.0"
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
rstest = "0.26.1"
